export const SKILLS = [
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Leadership",
  "Adaptability",
  "Time Management",
  "Critical Thinking",
    "Creativity",
    "Work Ethic",
    "Interpersonal Skills",
    "Emotional Intelligence",
    "Conflict Resolution",
    "Decision Making",
    "Stress Management",
    "Networking",
    "Public Speaking",
    "Negotiation",
    "Collaboration",
    "Active Listening",
    "Empathy",
    "Cultural Competence",
    "Self-Motivation",
    "Accountability",
    "Flexibility",
    "Positive Attitude",
    "Organization",
    "Goal Setting",
    "Resilience",
    "Mindfulness",
    "Feedback Reception",
];